version: '3.4'

services:

  db:
    container_name: sqlserver-db
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=@agesune1"
    ports:
      - "1433:1433"
    volumes:
      - .\data:/var/opt/mssql/data
      - .\log:/var/opt/mssql/log
